### PR TITLE
HCP specific settings

### PR DESCRIPTION
**Pull request by kitchell**
changes to allow for HCP specific settings

### CODE REVIEW

**Comment by francopestilli** [comment]
@soichih @kitchell I think I resolved a couple of merges conflicts here in this pull request. Please take a look at whether this makes sense. Thanks.

**Comment by kitchell** [comment]
@francopestilli I was in the middle of doing that, you've accepted the wrong changes. do you know how to undo this?

**Comment by kitchell** [comment]
I think i can just make a new pull request actually, might be easier!

**Comment by francopestilli** [comment]
Ok let's do that. I thought I made edits but did not really accept the pull request. I wanted your guys to accept my edits. So I am bit confused here. But starting over might be easiest.

**Comment by kitchell** [comment]
I am confused too! It looks like it wasn't accepted but idk how to edit
your edits. I'll figure it out

**Pull request closed without merging**
